export const GET_LOGIN_DATA = 'GET_LOGIN_DATA'
export const GET_LOGIN_DATA_SUCCESS = 'GET_LOGIN_DATA_SUCCESS'
export const GET_LOGIN_DATA_FAILURE = 'GET_LOGIN_DATA_FAILURE'
export const GET_PASSWORD_DATA = 'GET_PASSWORD_DATA'
export const GET_PASSWORD_DATA_SUCCESS ='GET_PASSWORD_DATA_SUCCESS'
export const GET_PASSWORD_DATA_FAILURE = 'GET_PASSWORD_DATA_FAILURE'
export const GET_SIGNUP_DATA = 'GET_SIGNUP_DATA'
export const GET_SIGNUP_DATA_SUCCESS = 'GET_SIGNUP_DATA_SUCCESS'
export const GET_SIGNUP_DATA_FAILURE = 'GET_SIGNUP_DATA_FAILURE'
export const GET_RESETPASSWORD_DATA = 'GET_RESETPASSWORD_DATA'
export const GET_RESETPASSWORD_DATA_SUCCESS = 'GET_RESETPASSWORD_DATA_SUCCESS'
export const GET_RESETPASSWORD_DATA_FAILURE = 'GET_RESETPASSWORD_DATA_FAILURE'


